version: '3.1'

services:
  beat_api:
    build: .
    ports:
      - ${BEAT_API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5182
    restart: always