version: '3.1'

services:
  redis-broker:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_UI_PORT}:8001"
    
  beat_db:
    image: postgres:alpine3.18
    ports:
      - 5432:${BEAT_DB_PORT}
    environment:
      - POSTGRES_DB=${BEAT_DB_NAME}
      - POSTGRES_USER=${BEAT_DB_USER}
      - POSTGRES_PASSWORD=${BEAT_DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  beat_api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - ${BEAT_API_PORT}:80
    environment:
      - ASPNETCORE_URLS=http://+
      - JwtSettings:Issuer=${BEAT_API_JWT_ISSUER}
      - JwtSettings:Audience=${BEAT_API_JWT_AUDIENCE}
      - JwtSettings:SecretKey=${BEAT_API_JWT_SECRET_KEY}
      - JwtSettings:AccessTokenExpirationInMinutes=${BEAT_API_JWT_ACCESS_TOKEN_EXPIRATION_IN_MINUTES}
      - JwtSettings:RefreshTokenExpirationInDays=${BEAT_API_JWT_REFRESH_TOKEN_EXPIRATION_IN_DAYS}
      - DbSettings:ConnectionString=${BEAT_API_CONNECTION_STRING}
      - MailSenderSettings:HostEmail=${BEAT_MAIL_HOST_EMAIL}
      - MailSenderSettings:SmtpServer=${BEAT_MAIL_SMTP_SERVER}
      - MailSenderSettings:SmtpPort=${BEAT_MAIL_SMTP_PORT}
      - MailSenderSettings:SmtpUser=${BEAT_MAIL_SMTP_USER}
      - MailSenderSettings:SmtpPassword=${BEAT_MAIL_SMTP_PASSWORD}
      - SmtpUser=${BEAT_MAIL_SMTP_USER}
      - SmtpPassword=${BEAT_MAIL_SMTP_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5182
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      beat_db:
        condition: service_healthy
      redis-broker:
        condition: service_started
    restart: always
