@host = localhost:5182
@token = AllProfilesResponeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDhhMDIzOC04Y2QzLTQ0NjEtYjlhMS1hNTk0NjU4MTcxNDQiLCJwcm9maWxlX2lkIjoiMTk3NjU5M2ItZDRhOC00YTVjLTgxZDAtNjUyNDY2ZTFiNzc5IiwiZW1haWwiOiJhbGV4QGdtYWkuY29tIiwiZ2l2ZW5fbmFtZSI6IkFsZXgiLCJhdmF0YXJfdXJsIjoicHVibGljL2RlZmF1bHRcXGRlZmF1bHQucG5nIiwibGV2ZWwiOiIwIiwibGV2ZWxfcGVyY2VudGFnZSI6IjAiLCJzdXN0YWluYWJsZV9wb2ludHMiOiIwIiwiZWNvX3Njb3JlIjoiMCIsImVjb19jb2lucyI6IjAiLCJjdXJyZW50X3hwIjoiMCIsIm5leHRfbGV2ZWxfeHAiOiIyNSIsImV4cCI6MTcxMjcwNzgzMCwiaXNzIjoiQmVhdEVjb3Byb3ZlIiwiYXVkIjoiQmVhdCBFY29wcm92ZSJ9.eNZWrZHz4VfoqwTu1POk4Tiw16nUNCq5T4W8svxKGpA

@search = ""
@page = 1
@pageSize = 100

GET /profiles/all?search={{search}}&page={{page}}&pageSize={{pageSize}} HTTP/1.1
Content-Type: application/json
Host: {{host}}
User-Agent: HTTPie
Authorization: Bearer {{token}}