@host = localhost:5182
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTE2Nzc4MC1iMTZjLTQ4OTMtOWI0MS0xYWNkMzQ3NmE0MjYiLCJwcm9maWxlX2lkIjoiNjVhMGE5NTEtYWRlNS00NTJiLWIzMmUtYzhlNDIxMTlmNmVhIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG5kb2UiLCJhdmF0YXJfdXJsIjoicHVibGljXFxkZWZhdWx0XFxkZWZhdWx0LnBuZyIsImxldmVsIjoiMCIsImxldmVsX3BlcmNlbnRhZ2UiOiIwIiwic3VzdGFpbmFibGVfcG9pbnRzIjoiMCIsImVjb19zY29yZSI6IjAiLCJlY29fY29pbnMiOiIwIiwiY3VycmVudF94cCI6IjAiLCJuZXh0X2xldmVsX3hwIjoiMjUiLCJleHAiOjE3MDk2MDE3MjUsImlzcyI6IkJlYXRFY29wcm92ZSIsImF1ZCI6IkJlYXQgRWNvcHJvdmUifQ.XQ78P2ceLjI395GuEmsMIxarAKXiYNotuj4Ojl8ufLs

PUT /profiles HTTP/1.1
Content-Type: multipart/form-data; boundary=PieBoundary123456789012345678901234567
Host: {{host}}
User-Agent: HTTPie
Authorization: Bearer {{token}}

--PieBoundary123456789012345678901234567
Content-Disposition: form-data; name="username"

Cristiano Ronaldo
--PieBoundary123456789012345678901234567
Content-Disposition: form-data; name="email"

cr7@email.com
--PieBoundary123456789012345678901234567
Content-Disposition: form-data; name="phone"

914444444
--PieBoundary123456789012345678901234567
Content-Disposition: form-data; name="postalCode"

4444-444
--PieBoundary123456789012345678901234567
Content-Disposition: form-data; name="avatarPicture"


--PieBoundary123456789012345678901234567--567