@host = localhost:5182
@token = value

POST /profiles/closet/bucket HTTP/1.1
Content-Length: 967
Content-Type: application/json
Host: {{host}}
Authorization: Bearer {{token}}
User-Agent: HTTPie

{
    "name" : "Bucket Name",
    "clothIds" : [
       "6f31568b-4f4c-432f-a8b6-4555437628dd",
       "34e6cc47-335a-47d5-8c5e-c4b99548dd13"
    ]
}