scrape_configs:
  - job_name: "beatecoprove"
    scheme: http
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: 
          - host.docker.internal:80
  - job_name: "prometheus"
    static_configs:
      - targets: 
          - localhost:9090